###########################################################################
#
# Makefile system for GILDAS softwares (2003-2012).
#
# Please be careful: element order often matters in makefiles.
#
###########################################################################

include $(gagadmdir)/Makefile.def

###########################################################################

EXECUTABLES = lclass

LOAD_LIBS = -llclass -lclass -lclassic $(ASTRO_LIBS) $(GREG_LIBS)

###########################################################################

include $(gagadmdir)/Makefile.main

###########################################################################
