###########################################################################
#
# Makefile system for GILDAS softwares (2003-2012).
#
# Please be careful: element order often matters in makefiles.
#
###########################################################################

include $(gagadmdir)/Makefile.def

###########################################################################

DOC_IDS = lclass

###########################################################################

include $(gagadmdir)/Makefile.doc

###########################################################################
lcalss.dvi lcalss.pdf lcalss-html: lclass.tex lclass-help-llas.tex
